# Dockerfile.r-python
FROM etretiakov/r-base:latest

LABEL maintainer="Evgenii Tretiakov <evgenii.tretiakov@meduniwien.ac.at>"

ARG DEBIAN_FRONTEND=noninteractive
ARG MINIFORGE_VERSION="24.7.1-2"
ARG PYTHON_VERSION=3.12
ENV CONDA_DIR /opt/conda
ENV PATH $CONDA_DIR/bin:$PATH
ENV CONDA_CUDA_OVERRIDE "12.4"
ARG PYTHON_SNAPSHOT='2024-12-01'
ARG R_VERSION=4.4.2
ARG R_SNAPSHOT='2024-12-01'
ENV QUARTO_VERSION "1.6.39"

# Copy Conda from python-base image
COPY --from=etretiakov/python-base /opt/conda /opt/conda
ENV PATH /opt/conda/bin:$PATH

# Install reticulate and configure
RUN /opt/R/${R_VERSION}/bin/Rscript -e \
	"pak::repo_add(CRAN = 'RSPM@${R_SNAPSHOT}');\
	pak::pkg_install(c(\
	'reticulate', \
	'quarto'))"
ENV RETICULATE_PYTHON /opt/conda/bin/python

RUN ${CONDA_DIR}/bin/pip config set global.index-url https://packagemanager.rstudio.com/pypi/${PYTHON_SNAPSHOT}/simple

RUN ${CONDA_DIR}/bin/mamba install  'ipykernel>=6.29.5' 'jupyterlab>=4.3.2' -y


RUN /opt/R/${R_VERSION}/bin/Rscript -e "IRkernel::installspec(user = FALSE)"

RUN ${CONDA_DIR}/bin/pip install --no-cache-dir jupyterlab-quarto

RUN ${CONDA_DIR}/bin/python -m ipykernel install

# After installing R and before installing Quarto
ENV QUARTO_R=/opt/R/${R_VERSION}/bin/R

# Install Quarto --------------------------------------------------------------#

RUN curl -o quarto-linux-amd64.deb -L https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.deb && \
	apt-get -qq update --fix-missing && \
	gdebi --non-interactive quarto-linux-amd64.deb && \
	/usr/local/bin/quarto check && \
	rm -rf quarto-linux-amd64.deb && \
	rm -rf /var/lib/apt/lists/*

CMD [ "/bin/bash" ]
