# Dockerfile.bioinfo
FROM etretiakov/posit-workbench:latest

LABEL maintainer="Evgenii Tretiakov <evgenii.tretiakov@meduniwien.ac.at>"

ARG DEBIAN_FRONTEND=noninteractive
ARG star_version="2.7.11b"
ARG samtools_version="1.21"
ARG bbmap_version="39.10"
ARG rsem_version="1.3.3"

# Install common system dependencies for bioinformatics tools
RUN apt-get update && \
	apt-get install -y --no-install-recommends \
	build-essential \
	zlib1g-dev \
	libncurses5-dev \
	libbz2-dev \
	liblzma-dev \
	libcurl4-openssl-dev \
	libssl-dev \
	&& rm -rf /var/lib/apt/lists/*

# Install specific bioinformatics tools if needed
# Install additional programs packages ----------------------------------------#

#Install STAR
RUN wget --no-check-certificate https://github.com/alexdobin/STAR/archive/refs/tags/${star_version}.tar.gz && \
	tar -xzf ${star_version}.tar.gz -C /opt && \
	cd /opt/STAR-${star_version}/source && \
	make STAR CXXFLAGS_SIMD="-msse4.2" && \
	cd / && rm ${star_version}.tar.gz

#Install seqtk
RUN git clone https://github.com/lh3/seqtk.git && \
	mv seqtk /opt && \
	cd /opt/seqtk && \
	make

#Install samtools
RUN wget https://github.com/samtools/samtools/releases/download/${samtools_version}/samtools-${samtools_version}.tar.bz2 && \
	tar -xvf samtools-${samtools_version}.tar.bz2 -C /opt && \
	cd /opt/samtools-${samtools_version} && \
	./configure && \
	make && \
	make install && \
	cd / && rm samtools-${samtools_version}.tar.bz2

#Install BBMap
RUN wget https://sourceforge.net/projects/bbmap/files/BBMap_${bbmap_version}.tar.gz && \
	tar -xzf BBMap_${bbmap_version}.tar.gz -C /opt && \
	cd /opt/bbmap && \
	./stats.sh in=resources/phix174_ill.ref.fa.gz && \
	cd / && rm BBMap_${bbmap_version}.tar.gz

#Install RSEM
RUN wget https://github.com/deweylab/RSEM/archive/refs/tags/v${rsem_version}.tar.gz && \
	tar -xzf v${rsem_version}.tar.gz -C /opt && \
	cd /opt/RSEM-${rsem_version} && \
	make && \
	cd / && rm v${rsem_version}.tar.gz

ENV PATH="${PATH}:/opt/STAR-${star_version}/source:/opt/seqtk:/opt/bbmap:/opt/RSEM-${rsem_version}"

#Saving Software Versions to a file
RUN echo "STAR version: ${star_version}" >> versions.txt && \
	echo "samtools version: ${samtools_version}" >> versions.txt && \
	echo "BBMap version: ${bbmap_version}" >> versions.txt && \
	echo "RSEM version: ${rsem_version}" >> versions.txt && \
	seqtk_version=`strings $(which seqtk) | grep 'Version:' | cut -f 2 -d " "` && \
	echo "seqtk version: ${seqtk_version}" >> versions.txt

# Install Gephi ---------------------------------------------------------------#

RUN mkdir gephi
RUN  wget https://github.com/gephi/gephi-toolkit/releases/download/v${GEPHI_VERSION}/gephi-toolkit-${GEPHI_VERSION}-all.jar && mv gephi-toolkit-${GEPHI_VERSION}-all.jar /gephi/
RUN  wget -c https://github.com/klarman-cell-observatory/forceatlas2/releases/download/${FA2_VERSION}/forceatlas2.jar && mv forceatlas2.jar /gephi/

# Install R-packages ----------------------------------------------------------#

RUN /opt/R/${R_VERSION}/bin/R -e \
	'pak::repo_add(CRAN = "RSPM@${R_SNAPSHOT}");\
	pak::pkg_install(c("SoupX"))'

# Install R packages
RUN /opt/R/${R_VERSION}/bin/Rscript -e 'BiocManager::install(c(\
	"anndata", \
	"annotation", \
	"AnnotationHub", \
	"AUCell", \
	"bacon", \
	"batchelor", \
	"Biostrings", \
	"BSgenome.Hsapiens.NCBI.GRCh38", \
	"BSgenome.Hsapiens.UCSC.hg19.masked", \
	"BSgenome.Hsapiens.UCSC.hg19", \
	"BSgenome.Hsapiens.UCSC.hg38.masked", \
	"BSgenome.Hsapiens.UCSC.hg38", \
	"BSgenome.Mmusculus.UCSC.mm10.masked", \
	"BSgenome.Mmusculus.UCSC.mm10", \
	"BSgenome.Rnorvegicus.UCSC.rn5", \
	"BSgenome", \
	"CARNIVAL", \
	"celldex", \
	"CellNOptR", \
	"chromVAR", \
	"CNORdt", \
	"CNORfeeder", \
	"CNORfuzzy", \
	"CNORode", \
	"CoGAPS", \
	"cosmosR", \
	"decoupleR", \
	"DESeq2", \
	"DropletUtils", \
	"edgeR", \
	"eisaR", \
	"EnhancedVolcano", \
	"enrichplot", \
	"EnsDb.Hsapiens.v86", \
	"EnsDb.Mmusculus.v79", \
	"fishpond", \
	"generegulation", \
	"GENIE3", \
	"GenomicAlignments", \
	"GenomicFeatures", \
	"GenomicRanges", \
	"glmGamPoi", \
	"harmony", \
	"Homo.sapiens", \
	"infercnv", \
	"IRanges", \
	"iSEE", \
	"iSEEu", \
	"JASPAR2020", \
	"kebabs", \
	"liftOver", \
	"limma", \
	"maftools", \
	"MAST", \
	"mistyR", \
	"MitoHEAR", \
	"MOFA2", \
	"MotifDb", \
	"motifmatchr", \
	"Nebulosa", \
	"nempi", \
	"OmnipathR", \
	"Organism.dplyr", \
	"pandaR", \
	"podkat", \
	"ReactomePA", \
	"rliger", \
	"rnaseqGene", \
	"Rsubread", \
	"rtracklayer", \
	"scAlign", \
	"scater", \
	"scBubbletree", \
	"schex", \
	"scone", \
	"SCpubr", \
	"scran", \
	"scry", \
	"Seurat", \
	"SingleR", \
	"slalom", \
	"slingshot", \
	"SomaticSignatures", \
	"SparseSignatures", \
	"SpatialFeatureExperiment", \
	"STRINGdb", \
	"sva", \
	"TFBSTools", \
	"TxDb.Hsapiens.UCSC.hg19.knownGene", \
	"TxDb.Hsapiens.UCSC.hg38.knownGene", \
	"TxDb.Mmusculus.UCSC.mm10.knownGene", \
	"tximport", \
	"veloviz", \
	"workflowr"\
	), dependencies = TRUE, upgrade_dependencies = TRUE, ask = FALSE)'

RUN --mount=type=secret,id=github_pat,dst=/tmp/github_pat /opt/R/${R_VERSION}/bin/R -e \
	'remotes::install_github(c(\
	"atakanekiz/CIPR-Package", \
	"bnprks/BPCells/r", \
	"cellgeni/sceasy", \
	"cellgeni/schard", \
	"chris-mcginnis-ucsf/DoubletFinder", \
	"cole-trapnell-lab/leidenbase", \
	"cole-trapnell-lab/monocle3", \
	"COMBINE-lab/roe", \
	"COMBINE-lab/wasabi", \
	"immunogenomics/harmony", \
	"immunogenomics/presto", \
	"JEFworks-Lab/CRAWDAD", \
	"JEFworks-Lab/MERINGUE", \
	"JEFworks-Lab/STdeconvolve", \
	"JEFworks-Lab/veloviz", \
	"JSB-UCLA/scDEED", \
	"JSB-UCLA/scPNMF", \
	"kharchenkolab/cacoa", \
	"kharchenkolab/conos", \
	"kharchenkolab/numbat", \
	"kharchenkolab/pagoda2", \
	"kharchenkolab/sccore", \
	"kharchenkolab/scistreer", \
	"kiangkiangkiang/ggESDA", \
	"KlugerLab/DAseq", \
	"mojaveazure/seurat-disk", \
	"morris-lab/Capybara", \
	"pachterlab/concordexR", \
	"pachterlab/voyager", \
	"pengminshi/mrtree", \
	"PoolLab/ReferenceEnhancer", \
	"sa-lee/plyranges", \
	"saezlab/CellNOptR-MaBoSS", \
	"saezlab/CNORprob", \
	"saezlab/decoupleR", \
	"saezlab/DOT", \
	"saezlab/liana", \
	"saezlab/ocean", \
	"saezlab/OmnipathR", \
	"saezlab/PHONEMeS-ILP", \
	"samuel-marsh/scCustomize", \
	"satijalab/azimuth", \
	"satijalab/seurat-data", \
	"satijalab/seurat-object", \
	"satijalab/seurat-wrappers", \
	"satijalab/seurat", \
	"ScialdoneLab/CIARA", \
	"single-cell-genetics/cardelino", \
	"slowkow/tftargets", \
	"sqjin/CellChat", \
	"stuart-lab/signac", \
	"Teichlab/sctkr", \
	"thackl/gggenomes", \
	"theislab/kBET", \
	"umbibio/CIE-R-Package", \
	"wilkox/gggenes", \
	"yanwu2014/swne", \
	"xmc811/Scillus@v0.5.0", \
	),\
	auth_token = readLines("/tmp/github_pat"), \
	dependencies = TRUE, \
	upgrade = "always")'

# Install with Conda ----------------------------------------------------------#

RUN mamba install --quiet -y \
	scvi-tools \
	snakemake \
	rpy2 \
	leidenalg \
	louvain \
	alevin-fry \
	salmon \
	bedtools \
	bedops \
	ffq \
	gget \
	gprofiler-official \
	macs3 \
	mygene \
	pybiomart \
	cellxgene \
	cellrank \
	celltypist \
	harmonypy \
	omnipath \
	ctxcore \
	decoupler-py \
	geosketch \
	squidpy \
	spatialdata \
	napari-spatialdata \
	spatialdata-io \
	spatialdata-plot \
	scrublet \
	sctriangulate \
	gffread && \
	conda clean -a -y


# Install with Pip ------------------------------------------------------------#

RUN ${CONDA_DIR}/bin/pip config set global.index-url https://packagemanager.rstudio.com/pypi/${PYTHON_SNAPSHOT}/simple

RUN ${CONDA_DIR}/bin/pip install --no-cache-dir \
	Cell-BLAST==0.5.1 \
	cello-classify==2.1.1 \
	ciara_python==1.0.4 \
	constclust==0.2.0 \
	gemmapy==1.0.7 \
	hidef==1.1.5 \
	liana==0.1.9 \
	louvain>=0.8.2 \
	pypath-omnipath==0.16.17 \
	pyscenic==0.12.1 \
	scplot==0.0.16


RUN	set -ex && \
	mamba upgrade --all \
	-c rapidsai -c pytorch -c nvidia && \
	mamba install --all \
	-c rapidsai -c pytorch -c nvidia \
	rapids=24.10 \
	cuda-version=12.4 \
	'pytorch=*=*cuda*' \
	torchvision \
	torchaudio \
	pytorch-cuda=12.4 \
	nx-cugraph=24.10 && \
	conda info -a

CMD [ "/bin/bash" ]
